# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lightrace < Formula
  desc "CLI for self-hosting Lightrace — LLM tracing and observability"
  homepage "https://github.com/SKE-Labs/lightrace"
  version "0.1.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.17/lightrace_0.1.17_darwin_amd64.tar.gz"
      sha256 "eb94658f90b97c9aa95a754dd81965d0702bacff427a5252517b34da2eda7f12"

      define_method(:install) do
        bin.install "lightrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.17/lightrace_0.1.17_darwin_arm64.tar.gz"
      sha256 "f16f7c6bebdc42bf8767c2cf1c5207d47fa3ba6c3e955485e67cb7013a6ccde7"

      define_method(:install) do
        bin.install "lightrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.17/lightrace_0.1.17_linux_amd64.tar.gz"
      sha256 "b6b6e3057eaca1b92a004b958a24b48e50e1c3c0d0f8c3a1e30077e00d5989a2"
      define_method(:install) do
        bin.install "lightrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.17/lightrace_0.1.17_linux_arm64.tar.gz"
      sha256 "2d23c6b1efbb11f9ca06265a352e314d0b34170b2cf39864e4b7fa6547a3c0db"
      define_method(:install) do
        bin.install "lightrace"
      end
    end
  end
end
