# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lightrace < Formula
  desc "CLI for self-hosting Lightrace — LLM tracing and observability"
  homepage "https://github.com/SKE-Labs/lightrace"
  version "0.1.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.14/lightrace_0.1.14_darwin_amd64.tar.gz"
      sha256 "6a8e4f263d9fabef74a0b63c2dbe8e052b6f5eaa609db39aac355130792ec40b"

      define_method(:install) do
        bin.install "lightrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.14/lightrace_0.1.14_darwin_arm64.tar.gz"
      sha256 "c95bfd26cd81fa725c52a40cd3002f38e22370c9b7570122a542e1379b21a316"

      define_method(:install) do
        bin.install "lightrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.14/lightrace_0.1.14_linux_amd64.tar.gz"
      sha256 "1efc35e4724e6387563589d5be9b01cbe288ad19df9f7a9f468f5c988e9bf40b"
      define_method(:install) do
        bin.install "lightrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.14/lightrace_0.1.14_linux_arm64.tar.gz"
      sha256 "25795d9b14b3c0b063bfe937440d7eab6775389216cc6a57342fe1013ed34817"
      define_method(:install) do
        bin.install "lightrace"
      end
    end
  end
end
