# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lightrace < Formula
  desc "CLI for self-hosting Lightrace — LLM tracing and observability"
  homepage "https://github.com/SKE-Labs/lightrace"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.2/lightrace_0.1.2_darwin_amd64.tar.gz"
      sha256 "c5149a1535e05704de52eeafc553380224ec22ad8605ee968113fe2c10bdfd7b"

      define_method(:install) do
        bin.install "lightrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.2/lightrace_0.1.2_darwin_arm64.tar.gz"
      sha256 "d4fdebcb575c73faf15f1b2ebb36a6f9d2d20572eb8e743d838503eda7803682"

      define_method(:install) do
        bin.install "lightrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.2/lightrace_0.1.2_linux_amd64.tar.gz"
      sha256 "482fcff066baf6f0d4dfa8ddfda565b91d03c746a45617c69ba50b165c0308cb"
      define_method(:install) do
        bin.install "lightrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SKE-Labs/lightrace-cli/releases/download/v0.1.2/lightrace_0.1.2_linux_arm64.tar.gz"
      sha256 "773980b9b510b476396f7d9cb1ab9bc543eeff8b4cdd10fec27f68d2cbdbb235"
      define_method(:install) do
        bin.install "lightrace"
      end
    end
  end
end
